spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_springboot
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "123456"
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop